#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t exthm"

$L "e"
$L "x"
$L "T" 
$L "H"
$L "m"
$L "U"
$L "I"
$L "Welcome to Android `getprop ro.build.version.release` / exTHmUI-`getprop ro.exthm.version`";
